# Generated by Django 5.2.7 on 2025-10-28 22:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlcanceSismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClasificacionSismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, unique=True)),
                ('kmProfundidadDesde', models.FloatField()),
                ('kmProfundidadHasta', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='EstacionSismologica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoEstacion', models.CharField(max_length=20, unique=True)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('nombre', models.CharField(blank=True, max_length=60, null=True)),
                ('documentoCertificacion', models.JSONField(blank=True, null=True)),
                ('fechaSolicitudCertificacion', models.DateTimeField(blank=True, null=True)),
                ('nroCertificacionAdquisicion', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('ambito', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='OrigenDeGeneracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeDato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.CharField(max_length=40, unique=True)),
                ('nombreUnidadDeMedida', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('nombre_mostrar', models.CharField(max_length=80)),
                ('password_hash', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='EventoSismico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHoraDeteccion', models.DateTimeField(default=django.utils.timezone.now)),
                ('magnitud', models.FloatField()),
                ('epi_lat', models.FloatField()),
                ('epi_lon', models.FloatField()),
                ('hipo_lat', models.FloatField()),
                ('hipo_lon', models.FloatField()),
                ('estado_actual_desde', models.DateTimeField(blank=True, null=True)),
                ('alcance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='redsismica.alcancesismo')),
                ('clasificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='redsismica.clasificacionsismo')),
                ('estado_actual', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_actuales', to='redsismica.estado')),
                ('origen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='redsismica.origendegeneracion')),
            ],
        ),
        migrations.CreateModel(
            name='CambioEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=60, null=True)),
                ('fechaHoraInicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fechaHoraFin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redsismica.estado')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios', to='redsismica.eventosismico')),
            ],
        ),
        migrations.CreateModel(
            name='SerieTemporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicionMarea', models.CharField(max_length=30)),
                ('fechaHoraInicioRegistroMuestras', models.DateTimeField()),
                ('fechaHoraFinRegistroMuestras', models.DateTimeField()),
                ('frecuenciaMuestreo', models.FloatField()),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='redsismica.eventosismico')),
            ],
        ),
        migrations.CreateModel(
            name='MuestraSismica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHoraMuestra', models.DateTimeField()),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muestras', to='redsismica.serietemporal')),
            ],
        ),
        migrations.CreateModel(
            name='Sismografo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nroSerie', models.CharField(max_length=30)),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sismografos', to='redsismica.estacionsismologica')),
            ],
        ),
        migrations.AddField(
            model_name='serietemporal',
            name='sismografo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_temporales', to='redsismica.sismografo'),
        ),
        migrations.CreateModel(
            name='DetalleMuestraSismica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('muestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='redsismica.muestrasismica')),
                ('tipoDato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles', to='redsismica.tipodedato')),
            ],
        ),
    ]
