# Generated by Django 5.2.7 on 2025-11-08 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redsismica', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estado',
            name='ambito',
        ),
    ]
