from typing import Protocol, List, Dict


class PantallaRevision():
    def habilitarPantalla(self) -> None: ...

    def solicitarSeleccionEventosSismicos(self, eventos: List[Dict]) -> None: ...

    def mostrarDatosEventoSismico(self, datos: Dict) -> None: ...

    def presentarAcciones(self, acciones: List[str]) -> None: ...
